name: libanga
favicon: null
layout_spectrum: 0.014967009192332625
typography_spectrum: 0.6653772643767297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7109547737054527
  lightness: 0.6612981101498008
  saturation: 0.17136053298600018
  rhythmicContrast: 0.7342466856352985
purpose: []
